version: "3.8"

volumes:
  media_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MEDIA_BASE}
  temp_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${TEMP_BASE} 