# This is the base configuration file that uses external volumes by default.
# For local storage options, use the appropriate docker-compose.local-*.yaml files
# See DEVELOPMENT.md for detailed documentation

version: "3.8"

x-volume-local: &volume-local
  driver: local
  driver_opts:
    type: none
    o: bind
    device: ${MEDIA_BASE}

x-volume-external: &volume-external
  external: true
  name: ${MEDIA_VOLUME_NAME}

services:
  bazarr:
    container_name: "${CONTAINER_NAME_PREFIX}_bazarr"
    image: "lscr.io/linuxserver/bazarr:${ARCH}-latest"
    entrypoint: ["/init"]
    env_file:
      - stack.env
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - "${CONFIG_BASE}/bazarr:/config"
      - "media_volume:${CONTAINER_MEDIA_PATH}:ro"
      - "media_volume:${CONTAINER_MEDIA_PATH_LEGACY}:ro"
    networks:
      - media_center_apps
    restart: unless-stopped

  calibre_web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: "${CONTAINER_NAME_PREFIX}_calibre_web"
    env_file:
      - stack.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - media_center_apps
    volumes:
      - "${CONFIG_BASE}/calibre-web:/config"
      - "media_volume:${CONTAINER_MEDIA_PATH}:ro"
      - "media_volume:${CONTAINER_MEDIA_PATH_LEGACY}:ro"
    restart: unless-stopped

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: "${CONTAINER_NAME_PREFIX}_calibre"
    env_file:
      - stack.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${CONFIG_BASE}/calibre:/config"
      - "media_volume:${CONTAINER_MEDIA_PATH}"
      - "media_volume:${CONTAINER_MEDIA_PATH_LEGACY}"
    restart: unless-stopped
    networks:
      - media_center_apps
    
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: "${CONTAINER_NAME_PREFIX}_readarr"
    env_file:
      - stack.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - media_center_apps
    volumes:
      - "${CONFIG_BASE}/readarr:/config"
      - "media_volume:${CONTAINER_MEDIA_PATH}:ro"
      - "media_volume:${CONTAINER_MEDIA_PATH_LEGACY}:ro"
      - "${TEMP_BASE}/readarr:/downloads"
    restart: unless-stopped

  jellyfin:
    container_name: "${CONTAINER_NAME_PREFIX}_jellyfin"
    image: "jellyfin/jellyfin"
    entrypoint: ["/jellyfin/jellyfin"]
    env_file:
      - stack.env
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_SERVER_URL}
      - TZ=${TZ}
    devices:
      - ${ROCKCHIP_DEVICE_DRI}
      - ${ROCKCHIP_DEVICE_DMA_HEAP}
      - ${ROCKCHIP_DEVICE_MALI}
      - ${ROCKCHIP_DEVICE_RGA}
      - ${ROCKCHIP_DEVICE_MPP}
    volumes:
      - "${CONFIG_BASE}/jellyfin-data:/config"
      - "${TEMP_BASE}/jellyfin:/cache"
      - "media_volume:${CONTAINER_MEDIA_PATH}:ro"
      - "media_volume:${CONTAINER_MEDIA_PATH_LEGACY}:ro"
    networks:
      media_center_apps:
      home_iot:
        ipv4_address: ${JELLYFIN_IP}
    privileged: ${ENABLE_ROCKCHIP_ACCELERATION}
    restart: unless-stopped

  jellyseerr:
    container_name: "${CONTAINER_NAME_PREFIX}_jellyseerr"
    image: "fallenbagel/jellyseerr:latest"
    entrypoint: ["/sbin/tini", "--"]
    command: ["pnpm", "start"]
    env_file:
      - stack.env
    environment:
      - TZ=${TZ}
      - PORT=${JELLYFIN_PORT}
      - LOG_LEVEL=${JELLYFIN_LOG_LEVEL}
    volumes:
      - "${CONFIG_BASE}/jellyseerr:/app/config"
    networks:
      - media_center_apps
    restart: unless-stopped

  qbittorrent:
    container_name: "${CONTAINER_NAME_PREFIX}_qbittorrent"
    image: "lscr.io/linuxserver/qbittorrent:${ARCH}-latest"
    entrypoint: ["/init"]
    env_file:
      - stack.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - TZ=${TZ}
    volumes:
      - "${CONFIG_BASE}/qbittorrent:/config"
      - "media_volume:${CONTAINER_MEDIA_PATH}"
      - "media_volume:${CONTAINER_MEDIA_PATH_LEGACY}"
      - "${TEMP_BASE}/qbittorrent:/temp"
    networks:
      - media_center_apps
    restart: unless-stopped

  radarr:
    container_name: "${CONTAINER_NAME_PREFIX}_radarr"
    image: "linuxserver/radarr:${ARCH}-develop"
    entrypoint: ["/init"]
    env_file:
      - stack.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${CONFIG_BASE}/radarr:/config"
      - "media_volume:${CONTAINER_MEDIA_PATH}:ro"
      - "media_volume:${CONTAINER_MEDIA_PATH_LEGACY}:ro"
    networks:
      - media_center_apps
    restart: unless-stopped

  sabnzbd:
    container_name: "${CONTAINER_NAME_PREFIX}_sabnzbd"
    image: "lscr.io/linuxserver/sabnzbd:${ARCH}-latest"
    entrypoint: ["/init"]
    env_file:
      - stack.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${CONFIG_BASE}/sabnzbd:/config"
      - "media_volume:${CONTAINER_MEDIA_PATH}"
      - "media_volume:${CONTAINER_MEDIA_PATH_LEGACY}"
      - "${TEMP_BASE}/sabnzbd:/temp"
    networks:
      - media_center_apps
    restart: unless-stopped

  sonarr:
    container_name: "${CONTAINER_NAME_PREFIX}_sonarr"
    image: "linuxserver/sonarr:${ARCH}-develop"
    entrypoint: ["/init"]
    env_file:
      - stack.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${CONFIG_BASE}/sonarr:/config"
      - "media_volume:${CONTAINER_MEDIA_PATH}:ro"
      - "media_volume:${CONTAINER_MEDIA_PATH_LEGACY}:ro"
    networks:
      - media_center_apps
    restart: unless-stopped

  cloudflared:
    container_name: "${CONTAINER_NAME_PREFIX}_cloudflared"
    image: "cloudflare/cloudflared:latest"
    entrypoint: ["cloudflared", "--no-autoupdate"]
    command: ["tunnel", "run"]
    env_file:
      - stack.env
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    networks:
      - media_center_apps
    restart: always
    deploy:
      replicas: ${ENABLE_CLOUDFLARED:-0}
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "--origincert", "/etc/cloudflared/cert.pem", "status"]
      interval: 120s
      timeout: 30s
      retries: 5
      start_period: 60s

  jellystat:
    container_name: "${CONTAINER_NAME_PREFIX}_jellystat"
    image: "cyfershepard/jellystat:latest"
    env_file:
      - stack.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYSTAT_JELLYFIN_URL=${JELLYFIN_SERVER_URL}
    volumes:
      - "${CONFIG_BASE}/jellystat:/app/data"
    networks:
      - media_center_apps
    restart: unless-stopped

networks:
  media_center_apps:
    name: "${MEDIA_CENTER_NETWORK}"
  home_iot:
    external: ${ENABLE_HOME_IOT_NETWORK:-false}
    name: "${HOME_IOT_NETWORK:-home_iot}"

volumes:
  media_volume:
    external: true
    name: ${MEDIA_VOLUME_NAME}
  config_volume:
    external: ${ENABLE_EXTERNAL_CONFIG_VOLUME:-true}
    name: ${CONFIG_VOLUME_NAME}
  temp_volume:
    external: ${ENABLE_EXTERNAL_TEMP_VOLUME:-true}
    name: ${TEMP_VOLUME_NAME}