version: "3.8"

services:
  jellyfin2:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin2
    healthcheck:
      disable: true
    privileged: true
    runtime: amd
    security_opt:
      - seccomp:unconfined
      - label=disable
      - apparmor=unconfined
    cap_add:
      - ALL
    environment:
      - PGID=911
      - PUID=911
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=https://media.home.bierlysmith.com
      - LIBVA_DRIVER_NAME=radeonsi
      - AMD_VISIBLE_DEVICES=all
    volumes:
      - media_center_jellyfin_config:/config
      - media_center_temp:/cache
      - media_center_media:/media
      - media_center_media:/media_legacy
      - /dev/dri:/dev/dri:z
    networks:
      - media_center_network
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.routers.jellyfin2-public.rule=Host(`${JELLYFIN_PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.jellyfin2-public.entrypoints=web,websecure"
      - "traefik.http.routers.jellyfin2-public.tls=true"
      - "traefik.http.routers.jellyfin2-public.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jellyfin2-public.service=jellyfin2"
      - "traefik.http.routers.jellyfin2-private.rule=Host(`${JELLYFIN_PRIVATE_DOMAIN}`)"
      - "traefik.http.routers.jellyfin2-private.entrypoints=web,websecure"
      - "traefik.http.routers.jellyfin2-private.tls=true"
      - "traefik.http.routers.jellyfin2-private.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jellyfin2-private.service=jellyfin2"
      - "traefik.http.services.jellyfin2.loadbalancer.server.port=8096"
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PGID=911
      - PUID=911
      - TZ=America/New_York
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - media_center_plex_config:/config
      - media_center_temp:/transcode
      - media_center_media:/media
      - media_center_media:/media_legacy
    networks:
      - media_center_network
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.routers.plex-public.rule=Host(`${PLEX_PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.plex-public.entrypoints=web,websecure"
      - "traefik.http.routers.plex-public.tls=true"
      - "traefik.http.routers.plex-public.tls.certresolver=letsencrypt"
      - "traefik.http.routers.plex-public.service=plex"
      - "traefik.http.routers.plex-private.rule=Host(`${PLEX_PRIVATE_DOMAIN}`)"
      - "traefik.http.routers.plex-private.entrypoints=web,websecure"
      - "traefik.http.routers.plex-private.tls=true"
      - "traefik.http.routers.plex-private.tls.certresolver=letsencrypt"
      - "traefik.http.routers.plex-private.service=plex"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
    restart: unless-stopped

networks:
  traefik_public:
    external: true
  media_center_network:
    external: true

volumes:
  media_center_jellyfin_config:
    external: true
  media_center_plex_config:
    name: "${CONTAINER_NAME_PREFIX}_plex_config"
    driver: local
    driver_opts:
      type: ${CONFIG_VOLUME_TYPE:-}
      o: ${CONFIG_VOLUME_OPTIONS:-}
      device: ${CONFIG_BASE}/plex
  media_center_temp:
    external: true
  media_center_media:
    external: true
