version: "3.8"

volumes:
  config_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CONFIG_BASE}

services:
  bazarr:
    volumes:
      - "${CONFIG_BASE}/bazarr:/config"

  calibre_web:
    volumes:
      - "${CONFIG_BASE}/calibre-web:/config"

  calibre:
    volumes:
      - "${CONFIG_BASE}/calibre:/config"

  readarr:
    volumes:
      - "${CONFIG_BASE}/readarr:/config"

  jellyfin:
    volumes:
      - "${CONFIG_BASE}/jellyfin-data:/config"

  jellyseerr:
    volumes:
      - "${CONFIG_BASE}/jellyseerr:/app/config"

  qbittorrent:
    volumes:
      - "${CONFIG_BASE}/qbittorrent:/config"

  radarr:
    volumes:
      - "${CONFIG_BASE}/radarr:/config"

  sabnzbd:
    volumes:
      - "${CONFIG_BASE}/sabnzbd:/config"

  sonarr:
    volumes:
      - "${CONFIG_BASE}/sonarr:/config"

  jellystat:
    volumes:
      - "${CONFIG_BASE}/jellystat:/app/data" 